<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\UserVMs\**" />
    <EmbeddedResource Remove="ViewModels\UserVMs\**" />
    <None Remove="ViewModels\UserVMs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Application\TaskFlow.Application.csproj" />
    <ProjectReference Include="..\TaskFlow.Infrastructure\TaskFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
